name: Erlang CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: [24, 25, 26]
        implementation: [rdrand, xorshift, pcg32]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run:  |
            sed -i "/^# deb.*universe/ s/^# //" /etc/apt/sources.list
            apt update
            apt -y install libgsl-dev
    - name: Compile
      run:  rebar3 as test compile
      env: 
        IMPLEMENTATION: ${{ matrix.implementation }}
    - name: Run tests
      run:  rebar3 as test proper
